apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    {{- include "admin-console.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install, pre-upgrade
    "helm.sh/hook-weight": "-3"
  name: kotsadm
