apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    {{- include "kots-helm.labels" . | nindent 4 }}
  name: kotsadm-confg
data:
  initial-app-images-pushed: "false"
  minio-enabled-snapshots: "false"
  registry-is-read-only: "false"
  skip-preflights: {{ .Values.kotsadm.automation.skipPreflights | quote }}

