apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "admin-console.labels" . | nindent 4 }}
  name: kotsadm
spec:
  ports:
  - name: http
    port: 3000
    targetPort: http
  selector:
    app: kotsadm
  type: ClusterIP
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "admin-console.labels" . | nindent 4 }}
  name: kotsadm-web
spec:
  ports:
  - name: http
    port: 8800
    nodePort: 3000
  selector:
    app: kotsadm
  type: LoadBalancer
status:
  loadBalancer: {}
