{{ if not .Values.adminConsole.minimalRBAC }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    {{- include "admin-console.labels" . | nindent 4 }}
  name: kotsadm-role
  annotations:
    "helm.sh/hook": pre-install, pre-upgrade
    "helm.sh/hook-weight": "-2"
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
{{ end }}
