apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy-kotsadm
  labels:
    app: proxy-kotsadm
spec:
  selector:
    matchLabels:
      app: proxy-kotsadm
  template:
    metadata:
      labels:
        app: proxy-kotsadm
    spec:
      containers:
      - name: proxy
        image: kotsadm/kurl-proxy:alpha
        env:
        - name: NODE_PORT
          value: "8800"
        - name: UPSTREAM_ORIGIN
          value: http://kotsadm:3000
        - name: DEX_UPSTREAM_ORIGIN
          value: http://kotsadm-dex:5556
        - name: TLS_SECRET_NAME
          value: kotsadm-tls
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        volumeMounts:
        - name: kotsadm-config
          mountPath: /etc/kotsadm
      serviceAccount: proxy
      volumes:
      - name: kotsadm-config
        configMap:
          name: kotsadm-application-metadata
          optional: true